version: '3.5'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      network: host
      context: .
    user: 1001:1001
    volumes:
      - ./static/config.json:/app/build/config.json:ro
    ports:
      - 9998:3000