# https://taskfile.dev

version: '3'

tasks:
  setup: 
    cmds:
      - npm install
      - npm install @openapitools/openapi-generator-cli 
  regen:
    cmds:
      - openapi-generator-cli generate -i ../bar.openapi.yml -g typescript-axios -o ./src/lib/api
