name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: cd backend && go mod download
      - name: Build
        run: cd backend && go build -v ./...
      - name: Test with the Go CLI
        run: cd backend && go test ./...